### ISSUE TITLE
Can you please upload your requirements.txt file.

### ISSUE THREAD

**Issue by imran2437** [DiracSpace/Django-Ecommerce-Site#12]

**Comment by DiracSpace** [comment]
If I recall correctly, the only extra libraries are the [here](https://github.com/DiracSpace/Django-Ecommerce-Site/blob/main/coronasecommerce/settings.py#L43-L44). You can install with the following:
* `sorl.thumbnail` -> `pip install sorl-thumbnail`
* `crispy_forms` -> `pip install django-crispy-forms`

All the other ones are already included in `Django`. But you do need to [install and configure Django with PostgreSQL](https://djangocentral.com/using-postgresql-with-django/) plus remember to change the [database credentials](https://github.com/DiracSpace/Django-Ecommerce-Site/blob/main/coronasecommerce/settings.py#L83-L92)
